# -*- coding: utf-8 -*-
"""Barabasi Albert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NMffqeJh4KOLAtzb-IE4TUnB0pcazUuY
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import networkx as nx
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
# %matplotlib inline

G = nx.barabasi_albert_graph(4039, 100, seed=None)

#degree-distribution
degs = {}
for n in G.nodes ():
    deg = G.degree (n)
    if deg not in degs :
        degs [deg ] = 0
    degs [deg] += 1
items = sorted ( degs . items ())
fig = plt.figure()
ax = fig.add_subplot (111)
ax.plot([k for (k,v) in items ], [v for (k,v) in items ])
#ax. set_xscale('log')
#ax. set_yscale('log')
plt.title("Facebook Degree Distribution")
plt.show()

#diameter
nx.diameter(G)

#Average shortest path length
nx.average_shortest_path_length(G)

#clustering-coefficient
nx.clustering(G)

#average-clustering-coefficient
nx.average_clustering(G)

#strongly-connected-components
for c in nx.strongly_connected_components(G):
  print(c)

#sparseness
nx.density(G)

#k-connectedness
c = nx.k_components(G,flow_func=None)
print(c)